// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ-KClIiyKt8BqlnNkZm4Sy6t3Gn0lbjU',
    appId: '1:767054586096:web:791903309563439ecf6235',
    messagingSenderId: '767054586096',
    projectId: 'curacare-9e157',
    authDomain: 'curacare-9e157.firebaseapp.com',
    storageBucket: 'curacare-9e157.firebasestorage.app',
    measurementId: 'G-RGYVWN85N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXF7wr1MXaOK-fK_NcsDYyvOPL0kipUI',
    appId: '1:767054586096:android:369fcba7ce49bc30cf6235',
    messagingSenderId: '767054586096',
    projectId: 'curacare-9e157',
    storageBucket: 'curacare-9e157.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB__aUND6l8J14AYwIg5vHofn62MseXqrk',
    appId: '1:767054586096:ios:41eef35cdf856917cf6235',
    messagingSenderId: '767054586096',
    projectId: 'curacare-9e157',
    storageBucket: 'curacare-9e157.firebasestorage.app',
    iosBundleId: 'com.example.curacare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB__aUND6l8J14AYwIg5vHofn62MseXqrk',
    appId: '1:767054586096:ios:41eef35cdf856917cf6235',
    messagingSenderId: '767054586096',
    projectId: 'curacare-9e157',
    storageBucket: 'curacare-9e157.firebasestorage.app',
    iosBundleId: 'com.example.curacare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ-KClIiyKt8BqlnNkZm4Sy6t3Gn0lbjU',
    appId: '1:767054586096:web:9f3dbd312b6a8f87cf6235',
    messagingSenderId: '767054586096',
    projectId: 'curacare-9e157',
    authDomain: 'curacare-9e157.firebaseapp.com',
    storageBucket: 'curacare-9e157.firebasestorage.app',
    measurementId: 'G-XW76G623XX',
  );
}

